apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "ran.hassid@gmail.com"
  # configure letencrypt's production api
  # replace with "https://acme-staging.api.letsencrypt.org/directory " to use the staging API
  lego.url: https://acme-v01.api.letsencrypt.org/directory